[package]
name = "actix-raft"
version = "0.4.3"
edition = "2018"
authors = ["Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"]
categories = ["algorithms", "asynchronous", "data-structures"]
description = "An implementation of the Raft distributed consensus protocol using the Actix actor framework."
documentation = "https://docs.rs/actix-raft"
homepage = "https://github.com/railgun-rs/actix-raft"
keywords = ["raft", "consensus", "data-storage"]
license = "MIT/Apache-2.0"
repository = "https://github.com/railgun-rs/actix-raft"
readme = "README.md"

[dependencies]
actix = "0.9.0"
bytes = "0.5.4"
futures = "0.3.4"
log = "0.4"
rand = "0.7.3"
serde = { version="1", features=["derive"] }
tokio = { version = "0.2", features = ["time"] }
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
async-log = "2"
env_logger = "0.7"
rmp = "0.8"
rmp-serde = "0.14"
tempfile = "3"

[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.
