on: [push, pull_request]
name: ci
jobs:
  build-async-raft:
    name: build async-raft
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # unit tests
      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --lib

      # integration tests
      - name: Integration Test | Initialization
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test initialization
      - name: Integration Test | NonVoter restart
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test non_voter_restart
      - name: Integration Test | Client Reads
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test client_reads
      - name: Integration Test | Client Writes
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test client_writes
      - name: Integration Test | Singlenode
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test singlenode
      - name: Integration Test | Dynamic Membership
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test dynamic_membership
      - name: Integration Test | Compaction
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test compaction
      - name: Integration Test | Current Leader
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test current_leader
      - name: Integration Test | Stepdown
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test stepdown
      - name: Integration Test | Shutdown
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test shutdown

      # release build
      - name: Build | Release Mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p async-raft --release

  build-async-raft-nightly:
    name: build async-raft nightly
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Build | Release Mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p async-raft --release --all-features

  build-memstore:
    name: build memstore
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # unit tests
      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p memstore

      # release build
      - name: Build | Release Mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p memstore --release

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings
